
services:
 test:
    image: test  # You can build this with the Dockerfile provided earlier
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_container
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              device_ids: ["3"]
    ports:
      - "8893:8888"
    shm_size: "1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /mnt/cxrscratch:/workingdir
      - /mnt/CXRReportCheckCohort:/data
    stdin_open: true
    tty: true
    restart: "no"