services:
  rrs_radsurv_processor:
    build: .
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - gpu
            count: all
            driver: nvidia
    environment:
      nifti_raw_MOUNT_POINT: /home/aa-cxk023/share/scratch/rrs_radsurv_processor_1751985584.065429
      nifti_raw_modalities_niiQuery.csv_MOUNT_POINT: /home/aa-cxk023/share/files
      preprocessed_MOUNT_POINT: /home/aa-cxk023/share/scratch/rrs_radsurv_processor_1751985584.065429
    image: rrs_radsurv_processor
    ipc: host
    ports:
    - 8003:8003
    stdin_open: true
    tty: true
    volumes:
    - /home/aa-cxk023/share/scratch/rrs_radsurv_processor_1751985584.065429:/scratch
    - /mnt/RadServiceCache/files:/files
    - /home/aa-cxk023/share/scratch/rrs_radsurv_processor_1751985584.065429/nifti_raw:/nifti_raw
    - /home/aa-cxk023/share/files/nifti_raw_modalities_niiQuery.csv:/nifti_raw_modalities_niiQuery.csv
    - /home/aa-cxk023/share/scratch/rrs_radsurv_processor_1751985584.065429/preprocessed:/preprocessed
    - /home/aa-cxk023/share/gbm_seg//active/RAD-AI-CNS-TUMOR-0104_20120619_rrs_radsurv.yaml:/script.yaml
volumes:
  files: null
  nifti_raw: null
  nifti_raw_modalities_niiQuery.csv: null
  preprocessed: null
  scratch: null
  script.yaml: null
