services:
  rrs_radsurv_processor:
    build: .
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - gpu
            count: all
            driver: nvidia
    environment:
      dicom_raw_MOUNT_POINT: /home/aa-cxk023/share/scratch/rrs_radsurv_processor_1754431223.7416158
      nifti_raw_MOUNT_POINT: /home/aa-cxk023/share/scratch/rrs_radsurv_processor_1754431223.7416158
      preprocessed_MOUNT_POINT: /home/aa-cxk023/share/scratch/rrs_radsurv_processor_1754431223.7416158
    image: rrs_radsurv_processor
    ipc: host
    ports:
    - 8003:8003
    stdin_open: true
    tty: true
    volumes:
    - /home/aa-cxk023/share/scratch/rrs_radsurv_processor_1754431223.7416158:/scratch
    - /mnt/RadServiceCache/files:/files
    - /home/aa-cxk023/share/scratch/rrs_radsurv_processor_1754431223.7416158/dicom_raw:/dicom_raw
    - /home/aa-cxk023/share/scratch/rrs_radsurv_processor_1754431223.7416158/nifti_raw:/nifti_raw
    - /home/aa-cxk023/share/scratch/rrs_radsurv_processor_1754431223.7416158/preprocessed:/preprocessed
    - /home/aa-cxk023/share/scratch/script.yaml:/script.yaml
volumes:
  dicom_raw: null
  files: null
  nifti_raw: null
  preprocessed: null
  scratch: null
  script.yaml: null
