services:
  radservice:
    env_file: ".env"
    build: .
    ports:
      - "8001:8001"
    volumes:
      - watch_folder:/mnt/RadServiceCache/idia_ingest_service/watch
      - scratch:/mnt/RadServiceCache/idia_ingest_service/scratch
volumes:
  watch_folder:
  scratch:

